services:
  app:
    image: ${DOCKER_USERNAME}/${APP_NAME}:${IMAGE_TAG}
    container_name: ${APP_NAME}${ENV_SUFFIX}-app
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILE}
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsS http://localhost:8080/actuator/health || wget -qO- http://localhost:8080/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 60s
    restart: unless-stopped
    networks:
      - app_network
    volumes:
      # 컨테이너의 로그 경로(/var/log/tomyongji/)를 호스트의 ./logs 폴더와 연결
      - ./app-logs:/var/log/tomyongji

  nginx:
    image: nginx:latest
    container_name: ${APP_NAME}${ENV_SUFFIX}-nginx
    depends_on:
      app:
        condition: service_healthy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    restart: unless-stopped
    command: >
      sh -c "
        echo 'Waiting for SSL certificate...';
        while ! test -f /etc/letsencrypt/live/${DOMAIN_NAME}/fullchain.pem; do
          sleep 5;
        done;
        echo 'Certificate found! Starting Nginx...';
        nginx -g 'daemon off;'
      "
    networks:
      - app_network

  certbot:
    image: certbot/certbot
    container_name: ${APP_NAME}${ENV_SUFFIX}-certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: >
      sh -c "while :; do certbot renew --webroot -w /var/www/certbot; sleep 12h; done"
    restart: unless-stopped
    networks:
      - app_network

  promtail:
    image: grafana/promtail:latest
    container_name: ${APP_NAME}${ENV_SUFFIX}-promtail
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml
      # app이 공유한 호스트의 ./app-logs 폴더를 Promtail 컨테이너의 /var/log/app 경로로 연결
      - ./app-logs:/var/log/app
      - promtail-data:/var/lib/promtail
    env_file: .env
    command: -config.file=/etc/promtail/config.yml
    restart: unless-stopped
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
volumes:
  promtail-data: